- hosts: pi
  become: true
  vars:
    ansible_ssh_user: pi
    ansible_ssh_pass: pi
    ansible_connection: ssh
    #source_key: "./.ssh/pi_id_rsa"
    #dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    # personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        update_cache: true
      tags:
        - install
        - dotfiles
        - stow
  tasks:
    # - include: tasks/core-setup.yml
    - name: Install zsh
      apt: name=zsh
      tags: &tags_for_zsh_tasks ["dotfiles", "zsh"]
    - name: Change shell
      shell: chsh -s `which zsh`
      become: yes
      tags: *tags_for_zsh_tasks
    - name: Check that the somefile.conf exists
      stat:
        path: /home/pi/.oh-my-zsh
      register: oh_my_stats
      tags: *tags_for_zsh_tasks
    - name: Install ohmyzsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      when: oh_my_stats.stat.exists == False
      become_user: pi
      tags: *tags_for_zsh_tasks
    - name: Install powerlevel10k
      ansible.builtin.git:
        repo: "https://github.com/romkatv/powerlevel10k.git"
        dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1
      become_user: pi
    - name: Install zsh-history-substring-search
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-history-substring-search"
        dest: "~/.oh-my-zsh/custom/plugins/zsh-history-substring-search"
        depth: 1
      become_user: pi
    - name: Install zsh-autosuggestions
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions"
        dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
      become_user: pi
    - name: Install zsh-syntax-highlighting
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
        dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
      become_user: pi
    - name: Download fzf
      become_user: pi
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf
        depth: 1
    - name: Check that the somefile.conf exists
      stat:
        path: /home/pi/.fzf
      register: fzf_stats
      tags: *tags_for_zsh_tasks
    - name: Install fzf
      become_user: pi
      shell: sudo ~/.fzf/install
      when: fzf_stats.stat.exists == False
    - name: Install fzf plugin
      become_user: pi
      ansible.builtin.git:
        repo: "https://github.com/unixorn/fzf-zsh-plugin.git"
        dest: "~/.oh-my-zsh/custom/plugins/fzf-zsh-plugin"
    - name: Installing stow
      apt: name=stow
      tags:
        - install
        - dotfiles
        - stow
    - name: Cloning .dotfiles
      become_user: pi
      ansible.builtin.git:
        repo: "https://github.com/arabshapt/.dotfiles.git"
        dest: "~/.dotfiles"
        recursive: yes
        update: yes
        accept_hostkey: yes
        version: master
      tags:
        - install
        - dotfiles
        - stow
    - name: Remove default .dotfiles
      shell: sudo rm -f .zshrc .bashrc .fzf.bash .fzf.zsh .p10k.zsh .vimrc .gitconfig .tmux.conf
    - name: Stow dotfiles
      shell: cd ~/.dotfiles && ./ubuntu
      become_user: pi
      tags:
        - install
        - dotfiles
        - stow
