- name: Install ZSH
  apt: name=zsh
  tags: &tags_for_zsh_tasks ["dotfiles", "zsh"]

- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

- name: Check that the somefile.conf exists
  stat:
    path: /home/arab/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False
  become_user: arab

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks

- name: Download fzf
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    depth: 1
  become: false

- name: Install fzf
  shell: sudo ~/.fzf/install
  become: false

- name: Install fzf plugin
  ansible.builtin.git:
    repo: "https://github.com/unixorn/fzf-zsh-plugin.git"
    dest: "~/.oh-my-zsh/custom}/plugins/fzf-zsh-plugin"
